### ISSUE TITLE
Suggestion / Request - Color coded circle | Partial tether

### ISSUE THREAD

**Issue by because-bot-fed** [PrincessRTFM/PositionalAssistant#3]
![image](https://user-images.githubusercontent.com/20569547/228742570-79974e91-c73f-4648-aa55-5fe1bed753ff.png)

Option to use a circle instead of lines. 
Configure thickness, color, and radius.
Replace full teather with a configurable length line that's centered on the circle but pointing between you and the target center. 

Hopefully the attached images work. 

![image](https://user-images.githubusercontent.com/20569547/228745721-b1c34208-fa0e-42a8-b703-cd3f809cd673.png)

![image](https://user-images.githubusercontent.com/20569547/228745771-65d53885-8322-4b71-89ef-6682156e53df.png)

just some examples of the idea

hope it's possible and not too much work and maybe something you'd be interested in adding

for context - my use case is "sometimes the existing circle is really hard to see"

but I'd like it better (and it'd honestly help me personally more) if it were in kinda the same style as the existing circle, just bigger/easier to see, and color coded :)

**Comment by VariableVixen** [comment]
I can definitely look into this. I've seen another plugin do partial arcs as well as PP's full circle, so I can almost definitely find existing methods to base things on. It'll take some time, but it should all be doable. The logic for arc length and colouration might be a little tricky though, I'll need to figure out how to handle that well.

**Comment by because-bot-fed** [comment]
Anything towards that result would be amazing :) thank you very much for your response and your efforts. 

I'm currently using the plugin as-is with the opacity turned way down to make it more subtle and it's working very nicely like that. Tremendous QoL for positionals. Thanks so much for making this in the first place. :D

**Comment by VariableVixen** [comment]
Glad you like it! I'm working on the partial tether feature first since it'll be _vastly_ simpler, and I think I almost have it working. The circle feature is... going to be a lot more complicated, but the configuration supports the necessary values at least.

Implementation details, as currently planned:
- The ring will have a "default" colour that will ONLY apply if NO lines are enabled. This will cause the ring to be drawn via ImGui, over the top of the game itself, which will make it visible even over VFX that would otherwise cover it.
- The ring will be split into **sixteen** arcs, with two arcs between each of the eight _possible_ guideline locations, so that each line has one arc to either side of it and each arc touches exactly one line.
- This is so that the colours of the arcs can be adjusted based on the lines that are enabled - the colour of the line will spread to the arcs adjacent to it, and any arcs attached to disabled lines will inherit their colour from the nearest enabled line.
- This means that if you have only two lines enabled (say, front and back) then the ring will be split into two colours, one covering each half. If you have four lines (for instance, the "cardinals" of front/back/left/right), you'll get a ring looking like your mockup image.
- In order to hide the lines while using the ring, set the minimum line size to 0 and the line modifier size to -128.
- It will not be possible to colour the ring sections and the lines separately, nor to hide only some lines and not others, because that would make things way too complicated. It's not _impossible_ to do, so maybe it'll come some day in the future, but it would require significant rewriting and redesigning of the settings window to essentially make each line independently configurable, and more still to make the ring section colours further independent.

Toggling the ring is already added to the command for the purposes of macros, although the code to actually _draw_ the ring hasn't been implemented yet.

**Comment by VariableVixen** [comment]
Partial tether is successfully implemented, I think. I'm not seeing any bugs with it, but I'm only looking at a training dummy at my FC's estate right now. I'll test it live in the wilds once I get the ring implemented, but that might take some time.

**Comment by VariableVixen** [comment]
Just waiting for the repo update now. As soon as that's done, the new features will be available.

**Comment by VariableVixen** [comment]
Okay, waiting for someone to help me with an icon for it, _then_ for the repo update

**Comment by because-bot-fed** [comment]
:bongocat: 

I'm excited! :D thanks again for all your work! :)

**Comment by VariableVixen** [comment]
![2023-04-01 08 46 58 557](https://user-images.githubusercontent.com/8753564/229308542-3aaf33a7-d860-41fb-a60d-8548d304f4e8.png)
Just need the repo maintainers to accept it!

**Comment by because-bot-fed** [comment]
I'm super stoked that looks awesome!

**Comment by because-bot-fed** [comment]
Just got in the game and updated and can confirm it's working and looks great! 
![image](https://user-images.githubusercontent.com/20569547/229959184-3f50c5c6-04bb-41dd-a4ba-b7f330fb0480.png)

Also stands out / separate enough from the normal ground circle that it seems to be almost always entirely/easily visible under all circumstances unlike the default stock target circle without the mod :) 

Thanks again so much for doing this, it looks great and I hope people like it :D

**Comment by VariableVixen** [comment]
For technical reasons, due to how plugins draw on the game, this circle will always be drawn _over_ all game effects that can obscure the vanilla one, so you should always be able to see it
