### ISSUE TITLE
3.2.0.32459 - Drawing at wrong height on some dummies

### ISSUE THREAD

**Issue by oorzkws** [PrincessRTFM/PositionalAssistant#5]
The version seems to have added a drawing error to some dummies. I've only been able to reproduce it in housing areas, I wasn't able to reproduce it in Summerford, Ultima Thule, Labyrinthos, or Yanxia.
![image](https://user-images.githubusercontent.com/65210810/230237317-01046a08-9009-4192-a8c6-146c330e4f80.png)

**Comment by VariableVixen** [comment]
There's a known bug in dalamud/FFXIV where striking dummies _may_ report the wrong height in their position. Unfortunately, there's nothing I can do in my plugin to fix this, since it's not in my code, and since they aren't _guaranteed_ to have the wrong position, I can't add a hack to work around it for the specific entities.

**Comment by oorzkws** [comment]
Fair enough, it's not your bug at the end of the day.

**Comment by VariableVixen** [comment]
If I _could_ do something about it, I would, but it's inconsistent so I can't even patch the render specifically on striking dummies because it doesn't always happen. For instance, I've never seen it on my own game.
